//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INLAY_EQUIPMENT
    {
        public int INTALY_ID { get; set; }
        public int ITEM_ID { get; set; }
        public Nullable<int> ITEM_COUNT { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual INLAY INLAY { get; set; }
    }
}
