//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOMS()
        {
            this.INLAY = new HashSet<INLAY>();
        }
    
        public int ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public Nullable<int> ROOM_FLOOR { get; set; }
        public Nullable<int> ROOM_TONNAGE { get; set; }
        public Nullable<int> ROOM_TYPE { get; set; }
    
        public virtual ROOM_TYPE ROOM_TYPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INLAY> INLAY { get; set; }
    }
}
